### ISSUE TITLE
[Bug]: "webp": No such file or directory

### ISSUE THREAD

**Issue by yoghurtlee-thu** [SalOne22/rimage#210] opened 2024-05-05 07:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As the title suggests.

When I try to compress the image using the config `webp` , it keeps telling me `"webp": No such file or directory (os error 2)` . Mozjpeg and so on fail to work either.

### Library Version

0.10.3

### Steps To Reproduce

1. Install rimage with the command `cargo install rimage` .
2. Direct to my target directory.
3. Run the command. 

### Anything else?

OS: macOS Sonoma

Rust version: cargo 1.77.2

**Comment by yoghurtlee-thu** [comment] 2024-05-05 07:40
Besides, I'm quite sure that the test image I used DOES exist.

**Comment by SalOne22** [comment] 2024-05-05 10:32
This is duplicate of #206 
Version 0.10.3 has different interface, try `rimage --help` to see available commands. Version 0.11.0 is still a pre-release, and I forgot about crates io. I pushed recent version to registry, you can install pre-release with this command: `cargo install rimage@0.11.0-next.0`

**Closed** 2024-05-05 10:39 UTC
Labels: bug
